logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


spring:
  rabbitmq:
    host: 192.168.126.7 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: hmall # 密码